<a href="https://colab.research.google.com/github/SherlynVironica/Praktikum/blob/main/Dekomposisi_LU_dan_eliminasi_Gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
S = np.array([[1,1,0,0],[1,1,1,0],[0,1,1,1],[1,0,1,0]])
G = np.array([[1,0,0,0,1,0,1],[0,1,0,0,1,1,1],[0,0,1,0,1,1,0],[0,0,0,1,0,1,1]])
P = np.array([[0,0,0,0,0,1,0],[1,0,0,0,0,0,0],[0,0,1,0,0,0,0],[0,1,0,0,0,0,0],
              [0,0,0,0,1,0,0],[0,0,0,0,0,0,1],[0,0,0,1,0,0,0]])


print(S)
print()
print(G)
print()
print(P)

[[1 1 0 0]
 [1 1 1 0]
 [0 1 1 1]
 [1 0 1 0]]

[[1 0 0 0 1 0 1]
 [0 1 0 0 1 1 1]
 [0 0 1 0 1 1 0]
 [0 0 0 1 0 1 1]]

[[0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]]


In [ ]:
SG = np.dot(A,B)
print(SG)

[[1 1 0 0 2 1 2]
 [1 1 1 0 3 2 2]
 [0 1 1 1 2 3 2]
 [1 0 1 0 2 1 1]]


In [ ]:
SS = np.array([[1,1,0,0,0,1,0],[1,1,1,0,1,0,0],[0,1,1,1,0,1,0],[1,0,1,0,0,1,1]])
print(SS)

[[1 1 0 0 0 1 0]
 [1 1 1 0 1 0 0]
 [0 1 1 1 0 1 0]
 [1 0 1 0 0 1 1]]


In [ ]:
SGP = np.dot(SS,P)
print(SGP)

[[1 0 0 0 0 1 1]
 [1 0 1 0 1 1 0]
 [1 1 1 0 0 0 1]
 [0 0 1 1 0 1 1]]


In [ ]:
AB = np.insert(A,[3],B,axis=1)
print(AB)

[[ 2  6  2  2]
 [-3 -8  0  2]
 [ 4  9  2  3]]


In [ ]:
AB[0,:] = AB[0,:]*(1/2) #1/2B1
print(AB)

[[ 1  3  1  1]
 [-3 -8  0  2]
 [ 4  9  2  3]]


In [ ]:
AB[2,:] = (-4)*AB[0,:] + AB[2,:]
print(AB)

[[ 1  3  1  1]
 [-3 -8  0  2]
 [ 0 -3 -2 -1]]


In [ ]:
AB[1,:] = 3*AB[0,:] + AB[1,:]
print(AB)

[[ 1  3  1  1]
 [ 0  1  3  5]
 [ 0 -3 -2 -1]]


In [ ]:
AB[2,:] = 3*AB[1,:] + AB[2,:]
print(AB)

[[ 1  3  1  1]
 [ 0  1  3  5]
 [ 0  0  7 14]]


In [ ]:
AB[2,:] = (1/7)*AB[2,:]
print(AB)

[[1 3 1 1]
 [0 1 3 5]
 [0 0 1 2]]


In [ ]:
AB[0,:] = (-3)*AB[1,:] + AB[0,:]
print(AB)

[[  1   0  -8 -14]
 [  0   1   3   5]
 [  0   0   1   2]]


In [ ]:
AB[0,:] = 8*AB[2,:] + AB[0,:]
print(AB)

[[1 0 0 2]
 [0 1 3 5]
 [0 0 1 2]]


In [ ]:
AB[1,:] = (-3)*AB[2,:] + AB[1,:]
print(AB)

[[ 1  0  0  2]
 [ 0  1  0 -1]
 [ 0  0  1  2]]


Sehingga nilai x1=2, x2=-1, dan x3=2

#Dekomposisi LU

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,6,2],[-3,-8,0],[4,9,2]])
B = np.array([[2],[2],[3]])

print(A)
print()
print(B)

[[ 2  6  2]
 [-3 -8  0]
 [ 4  9  2]]

[[2]
 [2]
 [3]]


In [ ]:
A[0,:] = (1/2)*A[0,:]
print(A)

[[ 1  3  1]
 [-3 -8  0]
 [ 4  9  2]]


In [ ]:
A[1,:] = 3*A[0,:] + A[1,:]
print(A)

[[1 3 1]
 [0 1 3]
 [4 9 2]]


In [ ]:
A[2,:] = (-4)*A[0,:] + A[2,:]
print(A)

[[ 1  3  1]
 [ 0  1  3]
 [ 0 -3 -2]]


In [ ]:
A[2,:] = 3*A[1,:] + A[2,:]
print(A)

[[1 3 1]
 [0 1 3]
 [0 0 7]]


In [ ]:
A[2,:] = (1/7)*A[2,:]
print(A)

[[1 3 1]
 [0 1 3]
 [0 0 1]]


In [ ]:
U = A
print(U)

[[1 3 1]
 [0 1 3]
 [0 0 1]]


In [ ]:
L1 = np.array([1/2,0,0])
L1_inv = np.array([2,0,0])
print(L1_inv)

[2 0 0]


In [ ]:
L2 = np.array([3,1,0])
L2_inv = np.array([-3,1,0])
print(L2_inv)

[-3  1  0]


In [ ]:
L3 = np.array([-4,0,1])
L3_inv = np.array([4,0,1])
print(L3_inv)

[4 0 1]


In [ ]:
L4 = np.array([0,3,1])
L4_inv = np.array([0,-3,1])
print(L4_inv)

[ 0 -3  1]


In [ ]:
L5 = np.array([0,0,1/7])
L5_inv = np.array([0,0,7])

In [ ]:
L6_inv = np.array([4,-3,7])

In [ ]:
L = np.array([L1_inv, L2_inv,L6_inv])
print(L)

[[ 2  0  0]
 [-3  1  0]
 [ 4 -3  7]]


In [ ]:
A = np.dot(L,U)
print(A)

[[ 2  6  2]
 [-3 -8  0]
 [ 4  9  2]]


#Dekomposisi LU Gauss

In [ ]:
L = np.array([[2,0,0],[-3,1,0],[4,-3,7]])
B = np.array([[2],[2],[3]])
C = np.insert(L,[3], B, axis=1)
print(C)

[[ 2  0  0  2]
 [-3  1  0  2]
 [ 4 -3  7  3]]


In [ ]:
C[0,:] = (1/2)*C[0,:]
print(C)

[[ 1  0  0  1]
 [-3  1  0  2]
 [ 4 -3  7  3]]


In [ ]:
C[1,:] = 3*C[0,:] + C[1,:]
print(C)

[[ 1  0  0  1]
 [ 0  1  0  5]
 [ 4 -3  7  3]]


In [ ]:
C[2,:] = (-4)*C[0,:] + C[2,:]
print(C)

[[ 1  0  0  1]
 [ 0  1  0  5]
 [ 0 -3  7 -1]]


In [ ]:
C[2,:] = 3*C[1,:] + C[2,:]
print(C)

[[ 1  0  0  1]
 [ 0  1  0  5]
 [ 0  0  7 14]]


In [ ]:
C[2,:] = 1/7*C[2,:]
print(C)

[[1 0 0 1]
 [0 1 0 5]
 [0 0 1 2]]


Y1=1, Y2=5, Y3=2

In [ ]:
U = np.array([[1,3,1],[0,1,3],[0,0,1]])
Y = np.array([[1],[5],[2]])

X = np.insert(U, [3], Y, axis=1)
print(X)

[[1 3 1 1]
 [0 1 3 5]
 [0 0 1 2]]


In [ ]:
X[0,:] = (-3)*X[1,:] + X[0,:]
print(X)

[[  1   0  -8 -14]
 [  0   1   3   5]
 [  0   0   1   2]]


In [ ]:
X[0,:] = (8)*X[2,:] + X[0,:]
print(X)

[[1 0 0 2]
 [0 1 3 5]
 [0 0 1 2]]


In [ ]:
X[1,:] = (-3)*X[2,:] + X[1,:]
print(X)

[[ 1  0  0  2]
 [ 0  1  0 -1]
 [ 0  0  1  2]]
