In [5]:
import numpy as np

tujuh tahun yang lalu umur Ani sama dengan 6 kali umur Budi. Empat tahun yang akan datang 2 kali umur Ani sama dengan 5 kali umur Budi di tambah dengan 9 tahun. Tentukan umur Budi dan Ani sekarang dengan menggunakan eliminasi Gauss!

In [8]:
# Definisikan ubah persamaan ke bentuk matriks A dan B
A = np.array ([[1, -6], [2, -5]])
B = np.array ([[7], [4]])

print (A)
print ()
print (B)

[[ 1 -6]
 [ 2 -5]]

[[7]
 [4]]


In [10]:
C = np.insert(A, [2], B, axis=1)
print (C)

[[ 1 -6  7]
 [ 2 -5  4]]


In [11]:
#-2B1+B2
C[1,:] = -2*C[0,:]+C[1,:]
print(C)

[[  1  -6   7]
 [  0   7 -10]]
