In [45]:
import numpy as np

In [46]:
# Mendefinisikan matriks A dan B berdasarkan persamaan
A = np.array([[1,1,-1], [1,2,1], [2,1,1]])
B = np.array([[-3], [7], [4]])

print(A)
print()
print(B)

[[ 1  1 -1]
 [ 1  2  1]
 [ 2  1  1]]

[[-3]
 [ 7]
 [ 4]]


In [47]:
# Mengubah matriks A menjadi U
U = A
print(U)

[[ 1  1 -1]
 [ 1  2  1]
 [ 2  1  1]]


In [48]:
#-2B2+B3
U[2,:] = (-2)*U[1,:]+U[2,:]
print(U)

[[ 1  1 -1]
 [ 1  2  1]
 [ 0 -3 -1]]


In [49]:
# -B1+B2
U[1,:] = (-1)*U[0,:]+U[1,:]
print(U)

[[ 1  1 -1]
 [ 0  1  2]
 [ 0 -3 -1]]


In [50]:
# 3B2+B3
U[2,:] = (3)*U[1,:]+U[2,:]
print(U)

[[ 1  1 -1]
 [ 0  1  2]
 [ 0  0  5]]


In [51]:

#menetukan L
L = np.array([[1,0,0],[1,1,0],[2,-1,1]])
print(L)

[[ 1  0  0]
 [ 1  1  0]
 [ 2 -1  1]]


In [52]:
# L U benar?
A = np.dot(L,U)
print (A)

[[ 1  1 -1]
 [ 1  2  1]
 [ 2  1  1]]
